### ISSUE TITLE
Rancher shell can't start with broken policy settings

### ISSUE THREAD

**Issue by kravciak** [kubewarden/namespace-label-propagator-policy#8]
### To reproduce
Create new policy (context-aware settings are broken in current UI, use them to break policy)
-> new ClusterAdmissionPolicy
-> Namespace label propagator (Protect mode)
-> fill name, add some label in settings

Wait until policy is active, then start kubectl shell. My UI generated this YAML:

<details><summary>Generated YAML</summary>

```yaml
apiVersion: policies.kubewarden.io.v1
kind: ClusterAdmissionPolicy
metadata:
  name: nlp
  namespace: ''
  annotations:
    artifacthub/pkg: namespace-label-propagator-policy/namespace-label-propagator-policy/0.1.2
spec:
  policyServer: default
  module: ghcr.io/kubewarden/policies/namespace-label-propagator:v0.1.2
  rules:
    - apiGroups:
        - ''
      apiVersions:
        - v1
      resources:
        - replicationcontrollers
        - pods
      operations:
        - CREATE
        - UPDATE
    - apiGroups:
        - apps
      apiVersions:
        - v1
      resources:
        - deployments
        - replicasets
        - statefulsets
        - daemonsets
      operations:
        - CREATE
        - UPDATE
    - apiGroups:
        - batch
      apiVersions:
        - v1
      resources:
        - jobs
        - cronjobs
      operations:
        - CREATE
        - UPDATE
  contextAware: false
  mutating: true
  settings:
    description: null
    propagatedLabels:
      - some-label
  mode: protect
ignoreRancherNamespaces: true
```
</details>

### Current result
kubectl shell does not start, required pod in cattle-system namespace is not created. Policyserver logs this message when I start kubectl shell:

```
2023-06-02T14:41:02.754557Z ERROR validation{host="policy-server-default-5895c59fc-dqqvm" policy_id="clusterwide-nlp" kind="Pod" kind_group="" kind_version="v1" name="" namespace="cattle-system" operation="CREATE" request_uid="7049580d-1247-4454-8f32-9e5d138c6ee1" resource="pods" resource_group="" resource_version="v1" subresource=""}:policy_eval:validate{self=PolicyEvaluator { id: "clusterwide-nlp", settings: {"propagatedLabels": Array [String("some-label")]} }}: policy_evaluator::runtimes::wapc: Policy tried to access a Kubernetes resource it doesn't have access to policy="clusterwide-nlp" resource_requested="v1/Namespace" resources_allowed={}
```

![Screenshot from 2023-06-02 16-37-05](https://github.com/kubewarden/namespace-label-propagator-policy/assets/538604/0faae39d-a3c2-4916-9312-5b87c07a9790)

### Expected result

Policy should ignore rancher resources even when it fails to start.
Rancher should be allowed to start a pod that is then connected to the UI.

```bash
~ k get pods -n cattle-system -o name
pod/dashboard-shell-69j7z
```
